{{ "{% set name =" | safe }} "{{ cookiecutter.package_import_name }}" {{ "%}" | safe }}
{{ "{% set version =" | safe }} "{{ cookiecutter.version }}" {{ "%}" | safe }}
{{ "{% set python_min =" | safe }} "{{ cookiecutter.min_python_version }}" {{ "%}" | safe }}

package:
  name: {{ "{{ name|lower }}" | safe }}
  version: {{ "{{ version }}" | safe }}

source:
  url: GENERATE_PYPI_URL
  sha256: {{ "GENERATE_SHA" | safe }}

build:
  noarch: python
  number: 0
  script: {{ "{{ PYTHON }}" }} -m pip install --no-deps --ignore-installed .
  entry_points:
    -  {{ cookiecutter.package_import_name }} = {{ cookiecutter.package_import_name }}.{{ cookiecutter.package_import_name.replace(".", "_").lower() }}_app:main

requirements:
  build:
    - GENERATE_BUILD_REQUIREMENTS

  host:
    - python {{ "{{ python_min }}" }}
    - GENERATE_HOST_REQUIREMENTS

  run:
    - python >={{ "{{ python_min }}" }}
    - GENERATE_RUN_REQUIREMENTS

test:
  requires:
    - python {{ "{{ python_min }}" }}
    - GENERATE_TEST_REQUIREMENTS

  source_files:
    - tests

  commands:
    - pip check
    - pytest

about:
  home: https://github.com/{{ cookiecutter.github_repo_name }}/{{ cookiecutter.github_repo_name }}/
  summary: {{ cookiecutter.project_short_description }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ cookiecutter.license_file }}
  description: |
    {{ cookiecutter.project_full_description }}
  doc_url: http://{{ cookiecutter.github_repo_name }}.github.io/{{ cookiecutter.github_repo_name }}/
  dev_url: https://github.com/{{ cookiecutter.github_repo_name }}/{{ cookiecutter.github_repo_name}}/

extra:
  recipe-maintainers:
    - GENERATE_MAINTAINERS
