name: Build Wheel, Release on GitHub, and Deploy Docs

on:
  workflow_dispatch:
  push:
    tags:
      - "*" # Trigger on all tags initially, but tag and release privilege are verified in _build-wheel-release-upload.yml

jobs:
  build-release:
    uses: scikit-package/release-scripts/.github/workflows/_build-release-github-no-pypi.yml@v0
    with:
      project: scikit-package-conda-forge
      c_extension: false
      maintainer_GITHUB_username: sbillinge
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
